# This is a basic workflow that is manually triggered

name: Work tools Frontend Deployment

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API..
on:
  push:
    branches:
      - master
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      name:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Deployment Comment'
        # Default value if no value is explicitly provided
        default: ' '
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  Deploy_to_Production:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
     # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    # Runs a single command using the runners shelltwo
    - name: Update docker image
      run: sudo docker build . -t localhost:32000/work-tools:registry --pull --no-cache
    - name: Push docker image to kubernetes registry
      run: sudo docker push localhost:32000/work-tools:registry
    - name: Deploy new image to kubernetes pod
      run: POD_NAME=$(command sudo microk8s kubectl get pods |grep -o '^\S*'|grep work-tools) && sudo microk8s kubectl delete pod $POD_NAME
    - name: Delete old docker images
      run: IMG_NAME=$(command docker images | grep none | awk '{print $3}') && docker rmi -f $IMG_NAME

